#!/bin/bash

# Init home dir
mkdir -pv /var/www/logs
chown -R www-data:www-data /var/www

echo Starting DBus
/etc/init.d/dbus start

echo Starting PHP-FPM
/etc/init.d/php5-fpm start

echo Starting Nginx
rm /var/www/nginx.sock 
nginx

sudo -u www-data /bin/bash entrypoint-www

echo "Let's go"
tail -f /var/www/logs/*

echo Stopping Container
